[package]
name = "overbot"
version = "0.1.0"
authors = ["OvermindDL1 <overminddl1@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
tokio = { version = "1.6", features = ["full"] }
rocket = { version = "0.5.0-dev", git = "https://github.com/SergioBenitez/Rocket.git" }